name: Release Build

on:
  push:
    branches:
      - main # 触发工作流的分支，可以根据需要修改
  release:
    types: [created] # 当有新Release被创建时触发

jobs:
  build:
    runs-on: ubuntu-latest # 使用Ubuntu环境来执行跨平台编译
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Build for Linux
      run: cargo build --release --target=x86_64-unknown-linux-gnu
    - name: Build for Windows
      run: cargo build --release --target=x86_64-pc-windows-gnu
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v3
      with:
        name: kk
        path: target/x86_64-unknown-linux-gnu/release/kk
    - name: Upload Windows Binary
      uses: actions/upload-artifact@v3
      with:
        name: kk 
        path: target/x86_64-pc-windows-gnu/release/kk.exe
